import { readFileSync } from "node:fs";
import { checkServerIdentity, type PeerCertificate } from "node:tls";

import { PrismaMariaDb } from "@prisma/adapter-mariadb";

import { PrismaClient } from "@/generated/prisma/client";

function adapterFromUrl(rawUrl: string) {
  let url: URL;
  try {
    url = new URL(rawUrl);
  } catch {
    throw new Error("Invalid server database configuration");
  }

  const database = decodeURIComponent(url.pathname.slice(1));
  if (url.protocol !== "mysql:" || !url.hostname || !url.username || !url.password || !database) {
    throw new Error("Invalid server database configuration");
  }
  if (!process.env.DB_TLS_CA_FILE)
    throw new Error("DB_TLS_CA_FILE is required for database access");

  const localAutoGeneratedCertificate =
    ["local", "test"].includes(process.env.APP_ENV ?? "") &&
    ["127.0.0.1", "localhost"].includes(url.hostname) &&
    url.port === "3307";
  const verifyServer = (hostname: string, certificate: PeerCertificate) =>
    localAutoGeneratedCertificate ? undefined : checkServerIdentity(hostname, certificate);
  const ssl = {
    ca: readFileSync(process.env.DB_TLS_CA_FILE),
    rejectUnauthorized: true,
    checkServerIdentity: verifyServer,
  };

  return new PrismaMariaDb({
    host: url.hostname,
    port: Number(url.port || 3306),
    user: decodeURIComponent(url.username),
    password: decodeURIComponent(url.password),
    database,
    timezone: "Z",
    connectionLimit: 5,
    ssl,
  });
}

export function createDatabaseClient(rawUrl: string) {
  if (typeof window !== "undefined") throw new Error("Database access is server-only");
  return new PrismaClient({ adapter: adapterFromUrl(rawUrl) });
}

const globalForDatabase = globalThis as typeof globalThis & {
  lessencDatabaseClient?: PrismaClient;
};

export function getDatabaseClient() {
  if (typeof window !== "undefined") throw new Error("Database access is server-only");
  if (!process.env.DB_RUNTIME_URL)
    throw new Error("DB_RUNTIME_URL is required for database access");
  globalForDatabase.lessencDatabaseClient ??= createDatabaseClient(process.env.DB_RUNTIME_URL);
  return globalForDatabase.lessencDatabaseClient;
}
